# (c) Dale Phurrough. All rights reserved.

name: "Raspberry Pi LED control"
description: >-
  Control LEDs (power, activity, ethernet, etc.) on Raspberry Pi
version: "0.1.30"
stage: experimental
slug: "dp_rpi_led_ctrl"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
machine:
  - raspberrypi3
  - raspberrypi3-64
  - raspberrypi4
  - raspberrypi4-64

# permissions
hassio_api: true
usb: true

# Claiming rating buff due to https://github.com/home-assistant/supervisor/blob/main/supervisor/addons/utils.py
# even though this addon has no incoming network access
auth_api: true

# TODO create services that can be called to adjust LEDs
startup: services
init: false

schema:
  "Power LED": bool
  "Activity LED trigger": list(none|mmc0)
  "Ethernet LEDs": bool

options:
  "Power LED": true
  "Activity LED trigger": 'mmc0'
  "Ethernet LEDs": true
